### ISSUE TITLE
Failed to load resource: the server responded with a status of 404.

### ISSUE THREAD

**Issue by reubenvickers** [kjb085/MMM-Reddit#21]
I'm running this module in the default suggested configuration from the README, however when I try to launch the mirror I get these errors in the console:

>:8080/modules/MMM_Reddit//MMM_Reddit.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)

>loader.js:187 script.onerror @ loader.js:187 Error on loading script: modules/MMM_Reddit//MMM_Reddit.js

I believe this must be an error in the module unless I am missing something.

**Comment by reubenvickers** [comment]
Fixed this by changing my .config file, must have been an error there

**Comment by andrewjohn3** [comment]
can you explain how you changed the .config file please. I am having the same issue.
