### ISSUE TITLE
Intermittent bug with 'show' set to 1: multiple images shown

### ISSUE THREAD

**Issue by jacobHclarkson** [kjb085/MMM-Reddit#3]
Using `displayType: 'image'` and `show: 1` with the module located at 'top_center', the current image gets frozen at the top and the module (seemingly after cycling through the entire set)  then cycles through images as usual immediately underneath the frozen image. After a while, things go back to normal, and then it breaks again as described.

This is my module config:
`
module: "MMM-Reddit",
position: "top_center",
config: {
subreddit: ['earthporn', 'abandonedporn', 'spaceporn'],
              displayType: 'image',
              imageQuality: 'high',
              count: 20,
               show: 1,
               width: 700,
               showAll: true,
}
`

The problem also occurs with only a single subreddit and for various values of width and count. Here is an [image](https://imgur.com/xBexLAR) of the problem happening.

**Comment by kjb085** [comment]
I've also come across this issue and is on the top of my list to debug, hopefully will be getting to it in the next couple of weeks.

**Comment by kjb085** [comment]
Did not mean to close the issue, sorry about that

**Comment by kjb085** [comment]
I have a bug fix for this that I've completed, I'm just going to give it 24 hours of use on my MM to make sure the other additional features which allows it to gracefully update by finishing the existing cycle before subbing in the new posts is working as expected. Sunday at latest until I merge my changes into master and push them up.

**Comment by kjb085** [comment]
Well, it was a little more than 24, but this bug has been fixed - please pull from master and confirm when you have a chance.

**Comment by kjb085** [comment]
Going to close this issue out. If you're still experiencing the bug, I will reopen.
